import Foundation

public struct InterfaceCopy: Equatable, Sendable {
    public let appTitle: String
    public let voiceInput: String
    public let systemAppleSpeech: String
    public let language: String
    public let interfaceLanguage: String
    public let recognitionLanguage: String
    public let outputLanguage: String
    public let listening: String
    public let readyToDictate: String
    public let startDictation: String
    public let stopDictation: String
    public let result: String
    public let emptyResult: String
    public let copyAction: String
    public let shareAction: String
    public let deviceSetup: String
    public let openIPhoneSettings: String
    public let microphoneTitle: String
    public let microphoneAllowed: String
    public let microphoneDenied: String
    public let speechRecognitionTitle: String
    public let speechEnabled: String
    public let speechDenied: String
    public let keyboardTitle: String
    public let keyboardDetail: String
    public let keyboardSetupTitle: String
    public let keyboardSetupDetail: String
    public let recentDictation: String
    public let clearHistory: String
    public let noRecentDictation: String
    public let useAction: String
    public let copiedToClipboard: String
    public let copiedHistoryItem: String
    public let checkingPermissions: String
    public let readyAuto: String
    public let permissionDisabled: String
    public let enablePermissions: String
    public let quickDictationRequested: String
    public let appleSpeechUnavailable: String
    public let createRequestFailed: String
    public let startMicFailed: String
    public let listeningPreferred: String
    public let listeningStatus: String
    public let recognized: String
    public let noSpeechDetected: String
    public let partialTranscriptSaved: String
    public let readyCopyShare: String
    public let historyCleared: String
    public let loadedFromHistory: String

    public static func localized(for language: LocalFlowLanguage) -> InterfaceCopy {
        switch language {
        case .english:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "Voice Input",
                systemAppleSpeech: "System Apple Speech",
                language: "Language",
                interfaceLanguage: "Interface",
                recognitionLanguage: "Recognition",
                outputLanguage: "Output",
                listening: "Listening",
                readyToDictate: "Ready to dictate",
                startDictation: "Start Dictation",
                stopDictation: "Stop Dictation",
                result: "Result",
                emptyResult: "Dictate first, then edit or share the result here.",
                copyAction: "Copy",
                shareAction: "Share",
                deviceSetup: "Device setup",
                openIPhoneSettings: "Open iPhone Settings",
                microphoneTitle: "Microphone",
                microphoneAllowed: "Allowed for this app.",
                microphoneDenied: "Allow microphone access in iPhone Settings.",
                speechRecognitionTitle: "Speech Recognition",
                speechEnabled: "Apple Speech permission is enabled.",
                speechDenied: "Allow speech recognition so Local Flow can transcribe through Apple Speech.",
                keyboardTitle: "Local Flow Keyboard",
                keyboardDetail: "Enable Local Flow Keyboard in Settings > General > Keyboard > Keyboards, then turn on Allow Full Access.",
                keyboardSetupTitle: "Enable Local Flow Keyboard",
                keyboardSetupDetail: "Settings > General > Keyboard > Keyboards > Add New Keyboard > Local Flow Keyboard, then enable Allow Full Access.",
                recentDictation: "Recent dictation",
                clearHistory: "Clear history",
                noRecentDictation: "No recent dictation yet.",
                useAction: "Use",
                copiedToClipboard: "Copied to clipboard.",
                copiedHistoryItem: "Copied history item.",
                checkingPermissions: "Checking permissions...",
                readyAuto: "Ready. Auto output keeps the speech language.",
                permissionDisabled: "Microphone or speech recognition permission is disabled.",
                enablePermissions: "Enable microphone and speech recognition in Settings.",
                quickDictationRequested: "Quick dictation requested.",
                appleSpeechUnavailable: "Apple Speech is unavailable right now.",
                createRequestFailed: "Could not create a speech recognition request.",
                startMicFailed: "Could not start microphone recording.",
                listeningPreferred: "Listening with iOS preferred speech language...",
                listeningStatus: "Listening...",
                recognized: "Recognized.",
                noSpeechDetected: "No speech detected. Try again.",
                partialTranscriptSaved: "Partial transcript saved.",
                readyCopyShare: "Ready to copy or share.",
                historyCleared: "History cleared.",
                loadedFromHistory: "Loaded from history."
            )
        case .simplifiedChinese:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "语音输入",
                systemAppleSpeech: "系统 Apple 语音识别",
                language: "语言",
                interfaceLanguage: "界面",
                recognitionLanguage: "识别",
                outputLanguage: "输出",
                listening: "正在聆听",
                readyToDictate: "可以开始听写",
                startDictation: "开始听写",
                stopDictation: "停止听写",
                result: "结果",
                emptyResult: "先开始听写，然后在这里编辑或分享结果。",
                copyAction: "复制",
                shareAction: "分享",
                deviceSetup: "设备设置",
                openIPhoneSettings: "打开 iPhone 设置",
                microphoneTitle: "麦克风",
                microphoneAllowed: "已允许此 App 使用。",
                microphoneDenied: "请在 iPhone 设置中允许麦克风权限。",
                speechRecognitionTitle: "语音识别",
                speechEnabled: "Apple 语音识别权限已启用。",
                speechDenied: "请允许语音识别，Local Flow 才能通过 Apple Speech 转写。",
                keyboardTitle: "Local Flow 键盘",
                keyboardDetail: "在 设置 > 通用 > 键盘 > 键盘 中启用 Local Flow Keyboard，然后打开完全访问。",
                keyboardSetupTitle: "启用 Local Flow 键盘",
                keyboardSetupDetail: "设置 > 通用 > 键盘 > 键盘 > 添加新键盘 > Local Flow Keyboard，然后启用完全访问。",
                recentDictation: "最近听写",
                clearHistory: "清空历史",
                noRecentDictation: "还没有最近听写。",
                useAction: "使用",
                copiedToClipboard: "已复制到剪贴板。",
                copiedHistoryItem: "已复制历史记录。",
                checkingPermissions: "正在检查权限...",
                readyAuto: "已就绪。自动输出会保持你说话的语言。",
                permissionDisabled: "麦克风或语音识别权限未开启。",
                enablePermissions: "请在设置中启用麦克风和语音识别权限。",
                quickDictationRequested: "已请求快速听写。",
                appleSpeechUnavailable: "Apple Speech 当前不可用。",
                createRequestFailed: "无法创建语音识别请求。",
                startMicFailed: "无法启动麦克风录音。",
                listeningPreferred: "正在使用 iOS 首选语音语言聆听...",
                listeningStatus: "正在聆听...",
                recognized: "识别完成。",
                noSpeechDetected: "没有检测到语音，请重试。",
                partialTranscriptSaved: "已保存部分转写。",
                readyCopyShare: "可以复制或分享。",
                historyCleared: "历史已清空。",
                loadedFromHistory: "已从历史记录载入。"
            )
        case .japanese:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "音声入力",
                systemAppleSpeech: "システム Apple Speech",
                language: "言語",
                interfaceLanguage: "表示言語",
                recognitionLanguage: "認識",
                outputLanguage: "出力",
                listening: "聞き取り中",
                readyToDictate: "音声入力できます",
                startDictation: "音声入力を開始",
                stopDictation: "音声入力を停止",
                result: "結果",
                emptyResult: "まず音声入力し、ここで編集または共有できます。",
                copyAction: "コピー",
                shareAction: "共有",
                deviceSetup: "デバイス設定",
                openIPhoneSettings: "iPhone設定を開く",
                microphoneTitle: "マイク",
                microphoneAllowed: "このアプリで許可されています。",
                microphoneDenied: "iPhone設定でマイクへのアクセスを許可してください。",
                speechRecognitionTitle: "音声認識",
                speechEnabled: "Apple Speechの権限が有効です。",
                speechDenied: "Apple Speechで文字起こしするには音声認識を許可してください。",
                keyboardTitle: "Local Flowキーボード",
                keyboardDetail: "設定 > 一般 > キーボード > キーボードでLocal Flow Keyboardを有効にし、フルアクセスをオンにします。",
                keyboardSetupTitle: "ローカルフローキーボードを有効にする",
                keyboardSetupDetail: "設定 > 一般 > キーボード > キーボード > 新しいキーボードを追加 > Local Flow Keyboardで、フルアクセスを有効にします。",
                recentDictation: "最近の音声入力",
                clearHistory: "履歴を消去",
                noRecentDictation: "最近の音声入力はまだありません。",
                useAction: "使用",
                copiedToClipboard: "クリップボードにコピーしました。",
                copiedHistoryItem: "履歴項目をコピーしました。",
                checkingPermissions: "権限を確認しています...",
                readyAuto: "準備完了。自動出力は話した言語を保持します。",
                permissionDisabled: "マイクまたは音声認識の権限が無効です。",
                enablePermissions: "設定でマイクと音声認識を有効にしてください。",
                quickDictationRequested: "クイック音声入力が要求されました。",
                appleSpeechUnavailable: "Apple Speechは現在利用できません。",
                createRequestFailed: "音声認識リクエストを作成できませんでした。",
                startMicFailed: "マイク録音を開始できませんでした。",
                listeningPreferred: "iOSの優先音声言語で聞き取り中...",
                listeningStatus: "聞き取り中...",
                recognized: "認識しました。",
                noSpeechDetected: "音声が検出されませんでした。もう一度お試しください。",
                partialTranscriptSaved: "部分的な文字起こしを保存しました。",
                readyCopyShare: "コピーまたは共有できます。",
                historyCleared: "履歴を消去しました。",
                loadedFromHistory: "履歴から読み込みました。"
            )
        case .korean:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "음성 입력",
                systemAppleSpeech: "시스템 Apple Speech",
                language: "언어",
                interfaceLanguage: "인터페이스",
                recognitionLanguage: "인식",
                outputLanguage: "출력",
                listening: "듣는 중",
                readyToDictate: "받아쓰기 준비됨",
                startDictation: "받아쓰기 시작",
                stopDictation: "받아쓰기 중지",
                result: "결과",
                emptyResult: "먼저 받아쓰기한 뒤 여기에서 편집하거나 공유하세요.",
                copyAction: "복사",
                shareAction: "공유",
                deviceSetup: "기기 설정",
                openIPhoneSettings: "iPhone 설정 열기",
                microphoneTitle: "마이크",
                microphoneAllowed: "이 앱에서 허용됨.",
                microphoneDenied: "iPhone 설정에서 마이크 접근을 허용하세요.",
                speechRecognitionTitle: "음성 인식",
                speechEnabled: "Apple Speech 권한이 활성화됨.",
                speechDenied: "Apple Speech로 전사하려면 음성 인식을 허용하세요.",
                keyboardTitle: "Local Flow 키보드",
                keyboardDetail: "설정 > 일반 > 키보드 > 키보드에서 Local Flow Keyboard를 추가한 뒤 전체 접근을 켜세요.",
                keyboardSetupTitle: "Local Flow 키보드 활성화",
                keyboardSetupDetail: "설정 > 일반 > 키보드 > 키보드 > 새로운 키보드 추가 > Local Flow Keyboard에서 전체 접근을 허용하세요.",
                recentDictation: "최근 받아쓰기",
                clearHistory: "기록 지우기",
                noRecentDictation: "최근 받아쓰기가 아직 없습니다.",
                useAction: "사용",
                copiedToClipboard: "클립보드에 복사됨.",
                copiedHistoryItem: "기록 항목이 복사됨.",
                checkingPermissions: "권한 확인 중...",
                readyAuto: "준비됨. 자동 출력은 말한 언어를 유지합니다.",
                permissionDisabled: "마이크 또는 음성 인식 권한이 꺼져 있습니다.",
                enablePermissions: "설정에서 마이크와 음성 인식 권한을 켜세요.",
                quickDictationRequested: "빠른 받아쓰기가 요청됨.",
                appleSpeechUnavailable: "Apple Speech를 지금 사용할 수 없습니다.",
                createRequestFailed: "음성 인식 요청을 만들 수 없습니다.",
                startMicFailed: "마이크 녹음을 시작할 수 없습니다.",
                listeningPreferred: "iOS 선호 음성 언어로 듣는 중...",
                listeningStatus: "듣는 중...",
                recognized: "인식됨.",
                noSpeechDetected: "음성이 감지되지 않았습니다. 다시 시도하세요.",
                partialTranscriptSaved: "부분 전사가 저장됨.",
                readyCopyShare: "복사하거나 공유할 수 있습니다.",
                historyCleared: "기록이 지워짐.",
                loadedFromHistory: "기록에서 불러옴."
            )
        case .traditionalChinese:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "語音輸入",
                systemAppleSpeech: "系統 Apple 語音辨識",
                language: "語言",
                interfaceLanguage: "介面",
                recognitionLanguage: "辨識",
                outputLanguage: "輸出",
                listening: "正在聆聽",
                readyToDictate: "可以開始聽寫",
                startDictation: "開始聽寫",
                stopDictation: "停止聽寫",
                result: "結果",
                emptyResult: "先開始聽寫，然後在這裡編輯或分享結果。",
                copyAction: "複製",
                shareAction: "分享",
                deviceSetup: "裝置設定",
                openIPhoneSettings: "打開 iPhone 設定",
                microphoneTitle: "麥克風",
                microphoneAllowed: "已允許此 App 使用。",
                microphoneDenied: "請在 iPhone 設定中允許麥克風權限。",
                speechRecognitionTitle: "語音辨識",
                speechEnabled: "Apple 語音辨識權限已啟用。",
                speechDenied: "請允許語音辨識，Local Flow 才能透過 Apple Speech 轉寫。",
                keyboardTitle: "Local Flow 鍵盤",
                keyboardDetail: "在 設定 > 一般 > 鍵盤 > 鍵盤 中啟用 Local Flow Keyboard，然後開啟完整取用。",
                keyboardSetupTitle: "啟用 Local Flow 鍵盤",
                keyboardSetupDetail: "設定 > 一般 > 鍵盤 > 鍵盤 > 加入新鍵盤 > Local Flow Keyboard，然後啟用完整取用。",
                recentDictation: "最近聽寫",
                clearHistory: "清空歷史",
                noRecentDictation: "還沒有最近聽寫。",
                useAction: "使用",
                copiedToClipboard: "已複製到剪貼簿。",
                copiedHistoryItem: "已複製歷史記錄。",
                checkingPermissions: "正在檢查權限...",
                readyAuto: "已就緒。自動輸出會保持你說話的語言。",
                permissionDisabled: "麥克風或語音辨識權限未開啟。",
                enablePermissions: "請在設定中啟用麥克風和語音辨識權限。",
                quickDictationRequested: "已請求快速聽寫。",
                appleSpeechUnavailable: "Apple Speech 目前不可用。",
                createRequestFailed: "無法建立語音辨識請求。",
                startMicFailed: "無法啟動麥克風錄音。",
                listeningPreferred: "正在使用 iOS 偏好的語音語言聆聽...",
                listeningStatus: "正在聆聽...",
                recognized: "辨識完成。",
                noSpeechDetected: "沒有偵測到語音，請重試。",
                partialTranscriptSaved: "已儲存部分轉寫。",
                readyCopyShare: "可以複製或分享。",
                historyCleared: "歷史已清空。",
                loadedFromHistory: "已從歷史記錄載入。"
            )
        case .french:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "Saisie vocale",
                systemAppleSpeech: "Apple Speech système",
                language: "Langue",
                interfaceLanguage: "Interface",
                recognitionLanguage: "Reconnaissance",
                outputLanguage: "Sortie",
                listening: "Écoute",
                readyToDictate: "Prêt à dicter",
                startDictation: "Démarrer la dictée",
                stopDictation: "Arrêter la dictée",
                result: "Résultat",
                emptyResult: "Dictez d'abord, puis modifiez ou partagez le résultat ici.",
                copyAction: "Copier",
                shareAction: "Partager",
                deviceSetup: "Configuration de l'appareil",
                openIPhoneSettings: "Ouvrir les réglages iPhone",
                microphoneTitle: "Microphone",
                microphoneAllowed: "Autorisé pour cette app.",
                microphoneDenied: "Autorisez le microphone dans les réglages iPhone.",
                speechRecognitionTitle: "Reconnaissance vocale",
                speechEnabled: "L'autorisation Apple Speech est activée.",
                speechDenied: "Autorisez la reconnaissance vocale pour transcrire avec Apple Speech.",
                keyboardTitle: "Clavier Local Flow",
                keyboardDetail: "Activez Local Flow Keyboard dans Réglages > Général > Clavier > Claviers, puis activez Accès complet.",
                keyboardSetupTitle: "Activer le clavier Local Flow",
                keyboardSetupDetail: "Réglages > Général > Clavier > Claviers > Ajouter un clavier > Local Flow Keyboard, puis activez Accès complet.",
                recentDictation: "Dictées récentes",
                clearHistory: "Effacer l'historique",
                noRecentDictation: "Aucune dictée récente.",
                useAction: "Utiliser",
                copiedToClipboard: "Copié dans le presse-papiers.",
                copiedHistoryItem: "Élément d'historique copié.",
                checkingPermissions: "Vérification des autorisations...",
                readyAuto: "Prêt. La sortie Auto conserve la langue parlée.",
                permissionDisabled: "Le microphone ou la reconnaissance vocale est désactivé.",
                enablePermissions: "Activez le microphone et la reconnaissance vocale dans les réglages.",
                quickDictationRequested: "Dictée rapide demandée.",
                appleSpeechUnavailable: "Apple Speech n'est pas disponible pour le moment.",
                createRequestFailed: "Impossible de créer une demande de reconnaissance vocale.",
                startMicFailed: "Impossible de démarrer l'enregistrement micro.",
                listeningPreferred: "Écoute avec la langue vocale préférée d'iOS...",
                listeningStatus: "Écoute...",
                recognized: "Reconnu.",
                noSpeechDetected: "Aucune voix détectée. Réessayez.",
                partialTranscriptSaved: "Transcription partielle enregistrée.",
                readyCopyShare: "Prêt à copier ou partager.",
                historyCleared: "Historique effacé.",
                loadedFromHistory: "Chargé depuis l'historique."
            )
        case .russian:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "Голосовой ввод",
                systemAppleSpeech: "Системный Apple Speech",
                language: "Язык",
                interfaceLanguage: "Интерфейс",
                recognitionLanguage: "Распознавание",
                outputLanguage: "Вывод",
                listening: "Слушаю",
                readyToDictate: "Готово к диктовке",
                startDictation: "Начать диктовку",
                stopDictation: "Остановить диктовку",
                result: "Результат",
                emptyResult: "Сначала продиктуйте текст, затем отредактируйте или поделитесь им здесь.",
                copyAction: "Копировать",
                shareAction: "Поделиться",
                deviceSetup: "Настройка устройства",
                openIPhoneSettings: "Открыть настройки iPhone",
                microphoneTitle: "Микрофон",
                microphoneAllowed: "Разрешено для этого приложения.",
                microphoneDenied: "Разрешите доступ к микрофону в настройках iPhone.",
                speechRecognitionTitle: "Распознавание речи",
                speechEnabled: "Разрешение Apple Speech включено.",
                speechDenied: "Разрешите распознавание речи для транскрибации через Apple Speech.",
                keyboardTitle: "Клавиатура Local Flow",
                keyboardDetail: "Включите Local Flow Keyboard в Настройки > Основные > Клавиатура > Клавиатуры, затем включите полный доступ.",
                keyboardSetupTitle: "Включить клавиатуру Local Flow",
                keyboardSetupDetail: "Настройки > Основные > Клавиатура > Клавиатуры > Новые клавиатуры > Local Flow Keyboard, затем включите полный доступ.",
                recentDictation: "Недавняя диктовка",
                clearHistory: "Очистить историю",
                noRecentDictation: "Недавней диктовки пока нет.",
                useAction: "Использовать",
                copiedToClipboard: "Скопировано в буфер обмена.",
                copiedHistoryItem: "Элемент истории скопирован.",
                checkingPermissions: "Проверка разрешений...",
                readyAuto: "Готово. Автовывод сохраняет язык речи.",
                permissionDisabled: "Микрофон или распознавание речи отключены.",
                enablePermissions: "Включите микрофон и распознавание речи в настройках.",
                quickDictationRequested: "Запрошена быстрая диктовка.",
                appleSpeechUnavailable: "Apple Speech сейчас недоступен.",
                createRequestFailed: "Не удалось создать запрос распознавания речи.",
                startMicFailed: "Не удалось начать запись с микрофона.",
                listeningPreferred: "Слушаю на предпочитаемом языке речи iOS...",
                listeningStatus: "Слушаю...",
                recognized: "Распознано.",
                noSpeechDetected: "Речь не обнаружена. Попробуйте снова.",
                partialTranscriptSaved: "Частичная транскрипция сохранена.",
                readyCopyShare: "Можно копировать или поделиться.",
                historyCleared: "История очищена.",
                loadedFromHistory: "Загружено из истории."
            )
        case .spanish:
            return InterfaceCopy(
                appTitle: "Local Flow",
                voiceInput: "Entrada de voz",
                systemAppleSpeech: "Apple Speech del sistema",
                language: "Idioma",
                interfaceLanguage: "Interfaz",
                recognitionLanguage: "Reconocimiento",
                outputLanguage: "Salida",
                listening: "Escuchando",
                readyToDictate: "Listo para dictar",
                startDictation: "Iniciar dictado",
                stopDictation: "Detener dictado",
                result: "Resultado",
                emptyResult: "Dicta primero y luego edita o comparte el resultado aquí.",
                copyAction: "Copiar",
                shareAction: "Compartir",
                deviceSetup: "Configuración del dispositivo",
                openIPhoneSettings: "Abrir ajustes del iPhone",
                microphoneTitle: "Micrófono",
                microphoneAllowed: "Permitido para esta app.",
                microphoneDenied: "Permite el acceso al micrófono en los ajustes del iPhone.",
                speechRecognitionTitle: "Reconocimiento de voz",
                speechEnabled: "El permiso de Apple Speech está activado.",
                speechDenied: "Permite el reconocimiento de voz para transcribir con Apple Speech.",
                keyboardTitle: "Teclado Local Flow",
                keyboardDetail: "Activa Local Flow Keyboard en Ajustes > General > Teclado > Teclados y luego activa Acceso total.",
                keyboardSetupTitle: "Activar el teclado Local Flow",
                keyboardSetupDetail: "Ajustes > General > Teclado > Teclados > Añadir nuevo teclado > Local Flow Keyboard, luego activa Acceso total.",
                recentDictation: "Dictado reciente",
                clearHistory: "Borrar historial",
                noRecentDictation: "Aún no hay dictados recientes.",
                useAction: "Usar",
                copiedToClipboard: "Copiado al portapapeles.",
                copiedHistoryItem: "Elemento del historial copiado.",
                checkingPermissions: "Comprobando permisos...",
                readyAuto: "Listo. La salida Auto conserva el idioma hablado.",
                permissionDisabled: "El micrófono o el reconocimiento de voz está desactivado.",
                enablePermissions: "Activa el micrófono y el reconocimiento de voz en Ajustes.",
                quickDictationRequested: "Dictado rápido solicitado.",
                appleSpeechUnavailable: "Apple Speech no está disponible ahora.",
                createRequestFailed: "No se pudo crear una solicitud de reconocimiento de voz.",
                startMicFailed: "No se pudo iniciar la grabación del micrófono.",
                listeningPreferred: "Escuchando con el idioma de voz preferido de iOS...",
                listeningStatus: "Escuchando...",
                recognized: "Reconocido.",
                noSpeechDetected: "No se detectó voz. Inténtalo de nuevo.",
                partialTranscriptSaved: "Transcripción parcial guardada.",
                readyCopyShare: "Listo para copiar o compartir.",
                historyCleared: "Historial borrado.",
                loadedFromHistory: "Cargado desde el historial."
            )
        }
    }
}
